# [순서]
# 업체 생성 > 업체 2개(공급, 생성)
# 업체 조회
# 공급, 생성 업체, 공급 업체 허브 Id
# 배송 담당자 생성(공급 업체 담당)
# 배송 담당자 조회(사용할 데이터는 없음. 잘 생성됬는가 확인)
# 주문 생성(공급, 생성 업체 Id 데이터에 넣기)
# 주문 조회
# 배송 조회
# 배송 경로 조회

@orderPort=8080
@deliveryPort=8081
@companyPort=8082
@deliverymanagerPort=8083

### 업체 생성 > 업체 2개(공급, 생성)
POST http://localhost:{{companyPort}}/company
Content-Type: application/json

{
  "hubId": "59d67615-c2b5-4971-9672-edda66e24932",
  "name": "컴퍼니3",
  "address": "서울특별시 강남구 테헤란로44길 8",
  "zipcode": "123456",
  "type": false
}

### 업체 조회
GET http://localhost:{{companyPort}}/company

### 공급, 생성 업체 Id
@supplyCompanyId=a41ac073-fb0d-47eb-8f96-a81109eebdef
@demandCompanyId=768c75d6-f941-45fd-a021-28b187587216
@deliveryManagerHubId=59d67615-c2b5-4971-9672-edda66e24930

### 배송 담당자 생성(공급 업체 담당)
POST http://localhost:{{deliverymanagerPort}}/deliverymanager
Content-Type: application/json

{
  "userId": 4,
  "hubId": "{{deliveryManagerHubId}}",
  "slackId": "5e6fa614-17c6-4a23-8bba-7bf05f11cd89",
  "type": "COMPANY_DELIVERY"
}

### 배송 담당자 조회(사용할 데이터는 없음. 잘 생성됬는가 확인)
GET http://localhost:{{deliverymanagerPort}}/deliverymanager

### 주문 생성(공급, 생성 업체 Id 데이터에 넣기)
POST http://localhost:{{orderPort}}/order
Content-Type: application/json

{
  "supplyCompanyId": "{{supplyCompanyId}}",
  "demandCompanyId": "{{demandCompanyId}}",
  "productId": "abcde123-4567-8901-abcd-1234567890ab",
  "amount": 100
}

### 주문 조회
GET http://localhost:{{orderPort}}/order

### 배송 조회
GET http://localhost:{{deliveryPort}}/delivery

### 배송 경로 조회
GET http://localhost:{{deliveryPort}}/deliveryroute