@DeliveryPort=8081
### Delivery Create - Send Post request with json body
POST http://localhost:{{DeliveryPort}}/delivery
Content-Type: application/json

{
  "orderId": "123e4567-e89b-12d3-a456-426614174000",
  "deliveryManagerId": "123e4567-e89b-12d3-a456-426614174001",
  "status": "WAIT_HUB",
  "startHubId": "123e4567-e89b-12d3-a456-426614174002",
  "endHubId": "123e4567-e89b-12d3-a456-426614174003",
  "address": "서울시 강남구 테헤란로 123",
  "recipientId": 10000123,
  "recipientSlackId": "U1234567"
}

### Delivery Get - Send Get request
GET http://localhost:{{DeliveryPort}}/delivery

### Delivery Get - Send Get request with path variable
@deliveryId=efbd40ad-0104-4f52-a346-e6e64934032e
GET http://localhost:{{DeliveryPort}}/delivery/{{deliveryId}}

### Delivery Update - Send Put request with path variable, json body
PUT http://localhost:{{DeliveryPort}}/delivery/{{deliveryId}}
Content-Type: application/json

{
  "deliveryManagerId": "123e4567-e89b-12d3-a456-426614174000",
  "startHubId": "123e4567-e89b-12d3-a456-426614174001",
  "endHubId": "123e4567-e89b-12d3-a456-426614174002",
  "address": "서울시 강남구 테헤란로 123",
  "recipientId": 10000123,
  "recipientSlackId": "U1234567",
  "status": "DELIVERY"
}


### Delivery Cancel - Send Delete request with path variable
DELETE http://localhost:{{DeliveryPort}}/delivery/{{deliveryId}}
