### Delivery Create - Send Post request with json body
POST http://localhost:8080/delivery
Content-Type: application/json

{
  "order_id": "123e4567-e89b-12d3-a456-426614174000",
  "delivery_manager_id": "123e4567-e89b-12d3-a456-426614174001",
  "status": "WAIT_HUB",
  "start_hub_id": "123e4567-e89b-12d3-a456-426614174002",
  "end_hub_id": "123e4567-e89b-12d3-a456-426614174003",
  "address": "서울시 강남구 테헤란로 123",
  "recipient_id": 10000123,
  "recipient_slack_id": "U1234567"
}


### Delivery Update - Send Put request with path variable, json body
@deliveryId=efbd40ad-0104-4f52-a346-e6e64934032e
PUT http://localhost:8080/delivery/{{deliveryId}}
Content-Type: application/json

{
  "delivery_manager_id": "123e4567-e89b-12d3-a456-426614174000",
  "start_hub_id": "123e4567-e89b-12d3-a456-426614174001",
  "end_hub_id": "123e4567-e89b-12d3-a456-426614174002",
  "address": "서울시 강남구 테헤란로 123",
  "recipient_id": 10000123,
  "recipient_slack_id": "U1234567",
  "status": "DELIVERY"
}


### Delivery Cancel - Send Delete request with path variable
#DELETE http://localhost:8080/delivery/{{deliveryId}}
