@DeliveryRoutePort=8081
### Delivery Create - Send Post request with json body
POST http://localhost:{{DeliveryRoutePort}}/deliveryroute
Content-Type: application/json

[
  {
    "deliveryId": "d5e1b123-8f9c-4d3b-a0c1-fc97e3b8a5bc",
    "sequence": 1,
    "startHubId": "e3d4f5a1-22b7-4f97-bd5c-2b67b8d2a1c4",
    "endHubId": "e2d5c7f8-3b4a-4c5d-9e1f-6a8c9b0d2e5b",
    "estimatedDistance": 100,
    "estimatedTime": 60,
    "realDistance": 90,
    "realTime": 50,
    "status": "DELIVERY"
  },
  {
    "deliveryId": "d5e1b123-8f9c-4d3b-a0c1-fc97e3b8a5bc",
    "sequence": 2,
    "startHubId": "e2d5c7f8-3b4a-4c5d-9e1f-6a8c9b0d2e5b",
    "endHubId": "f4d9a5b7-6c3b-4d8a-b1f2-7e9c3d8a2e6b",
    "estimatedDistance": 120,
    "estimatedTime": 70,
    "realDistance": 105,
    "realTime": 60,
    "status": "WAIT_HUB"
  }
]

### DeliveryRoute Get - Send Get request
GET http://localhost:{{DeliveryRoutePort}}/deliveryroute

### DeliveryRoute Get - Send Get request with path variable
@deliveryRouteId=53e0d99e-d292-45c6-942f-30a3b92ed82b
GET http://localhost:{{DeliveryRoutePort}}/deliveryroute/{{deliveryRouteId}}

### DeliveryRoute Update - Send Put request with path variable, json body
PUT http://localhost:{{DeliveryRoutePort}}/deliveryroute/{{deliveryRouteId}}
Content-Type: application/json

{
  "realDistance": 90,
  "realTime": 50,
  "status": "MOVE_HUB"
}

### DeliveryRoute Cancel - Send Delete request with path variable
DELETE http://localhost:{{DeliveryRoutePort}}/deliveryroute/{{deliveryRouteId}}
