### HubRoute Create - Send Post request with json body
POST http://localhost:8080/hubRoute
Content-Type: application/json

{
  "prevHubRouteId": "f0a25ca1-3e0d-4118-862e-e07f4ce95ff8",
  "currentHubId": "a805c1de-5fb9-45ac-94cd-be8ce2d51dac",
  "time" : 20
}

### HubRoute Get - Send Get request with Path Variable
< {%
    request.variables.set("hubRouteId", "6247f4f1-a84b-4506-bcab-3d7b797b46f5")
%}
GET http://localhost:8080/hubRoute/{{hubRouteId}}

### HubRoute Get - Send Get request
GET http://localhost:8080/hubRoute

### HubRoute Update - Send Update Request
PUT http://localhost:8080/hubRoute
Content-Type: application/json

{
  "hubRouteId" : "6247f4f1-a84b-4506-bcab-3d7b797b46f5",
  "nextHubRouteId" :  "f0a25ca1-3e0d-4118-862e-e07f4ce95ff8",
  "prevHubRouteId" :  "aab3cca5-6382-46d4-979f-f1804c6b4ff0",
  "time" :  20
}
