server:
  port: 19091

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
      discovery:
        locator:
          enabled: true
  data:
    redis:
      host: localhost  # Redis 서버의 호스트명
      port: 6379       # Redis 서버 포트
      username: default
      password: systempass

service:
  jwt:
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/