@userPort=8080
@orderPort=8080
@token=Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJuYW1lIjoibmV3bmFtZSIsInN1YiI6ImVtYWlsQGVtYWlsLmNvbSIsInJvbGUiOiJNQVNURVIiLCJleHAiOjE3MjYxNjMyMzQsImlhdCI6MTcyNjE1OTYzNH0.o3PEhGm6v6BuT0SWPqEVjN41Sbv8GwK9_SE5dw7iMgA

### Order Create - Send Post request with json body
POST http://localhost:{{orderPort}}/order
Content-Type: application/json
Authorization: {{token}}

{
  "supplyCompanyId": "a41ac073-fb0d-47eb-8f96-a81109eebdef",
  "demandCompanyId": "768c75d6-f941-45fd-a021-28b187587216",
  "productId": "abcde123-4567-8901-abcd-1234567890ab",
  "amount": 100
}

### Order Get - Send Get request
GET http://localhost:{{orderPort}}/order
Authorization: {{token}}

### Order Find Get - Send Get request with path variable
@orderId=5145738c-6576-4cf2-9821-81e82e253851
GET http://localhost:{{orderPort}}/order/{{orderId}}

### Order Update - Send Put request with path variable, json body
PUT http://localhost:{{orderPort}}/order/{{orderId}}
Content-Type: application/json

{
  "deliveryId": "987e6543-e21b-12d3-a456-426614174001",
  "amount": 200,
  "status": "DELIVERY"
}

### Order Cancel - Send Delete request with path variable
DELETE http://localhost:{{orderPort}}/order/{{orderId}}

### User SignIn - Send Post request with json body
POST http://localhost:{{userPort}}/user/signIn
Content-Type: application/json

{
  "name": "newname",
  "password": "new_password"
}