@userPort=8080
### User SignUp - Send Post request with json body
POST http://localhost:{{userPort}}/user/signUp
Content-Type: application/json

{
  "name": "newname2",
  "password": "new_password",
  "email": "email2@email.com",
  "tel": "010-9173-9506",
  "role": "MASTER"
}

### User SignIn - Send Post request with json body
POST http://localhost:{{userPort}}/user/signIn
Content-Type: application/json

{
  "name": "newname",
  "password": "new_password"
}