@DeliveyManagerPort=8083
### DeliveryManager Create - Send Post request with json body
POST http://localhost:{{DeliveyManagerPort}}/deliverymanager
Content-Type: application/json

{
  "userId": 3,
  "hubId": "59d67615-c2b5-4971-9672-edda66e24930",
  "slackId": "5e6fa614-17c6-4a23-8bba-7bf05f11cd89",
  "type": "COMPANY_DELIVERY"
}

### DeliveryManager Get - Send Get request
GET http://localhost:{{DeliveyManagerPort}}/deliverymanager

### DeliveryManager Find Get - Send Get request with path variable
@deliveryManagerId=8d2ef67e-553f-48e9-9a23-91bfa8eb00b3
GET http://localhost:{{DeliveyManagerPort}}/deliverymanager/{{deliveryManagerId}}

### DeliveryManager Find Get Hub Id - Send Get request with path variable
@hubId=59d67615-c2b5-4971-9672-edda66e24930
GET localhost:{{DeliveyManagerPort}}/deliverymanager/hub/{{hubId}}

### DeliveryManager Update - Send Put request with path variable, json body
PATCH http://localhost:{{DeliveyManagerPort}}/deliverymanager/{{deliveryManagerId}}
Content-Type: application/json

{
  "hubId": "5e6fa614-17c6-4a23-8bba-7bf05f11cd89",
  "type": "COMPANY_DELIVERY"
}

### Order Cancel - Send Delete request with path variable
DELETE http://localhost:{{DeliveyManagerPort}}/deliverymanager/{{deliveryManagerId}}
